#pragma once

#define BACKLIGHT_LEVELS 5
#define BACKLIGHT_LIMIT_VAL 200
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define TAPPING_TERM 250
#define TAPPING_TOGGLE 2
