#pragma once

#define BACKLIGHT_DEFAULT_LEVEL 4
#define BACKLIGHT_LEVELS 10
#define BACKLIGHT_LIMIT_VAL 255
#define PERMISSIVE_HOLD
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define TAPPING_TERM 220
#define TAPPING_TOGGLE 3
